### ISSUE TITLE
backwards compatible

### ISSUE THREAD

**Issue by renedeboer** [ibericode/vat-bundle#11]
you removed in VatNumber.php 2.0.9
/**
 * @Annotation
 */

Is it possible to leave it here for backward compatible?
Need a lot of time to convert all my annotations to attributes, but will do :-)

**Comment by dannyvankooten** [comment]
Hello,

I’d just pin the package to the version that still supports annotations. But on another note, I wholeheartedly recommend Rector for replacing all annotations with attributes. It turned several tedious hours of work into a 10-minute job for me: https://www.dannyvankooten.com/blog/2023/rector-annotations-to-attributes/
