### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by benconda** [ibericode/vat-bundle#14]
Hi, the symfony 7 blocker has been fixed. 

Wonder when do you plan to do a release so it's no more a blocker for the SF 7 upgrade on project using this bundle? (currently need to target master which is not ideal) 

Thank you :pray:

**Comment by dannyvankooten** [comment]
Hello,

There's currently [a failing job](https://github.com/ibericode/vat-bundle/actions/runs/8861627839/job/24333700643), which would normally indicate things are not yet working with Symfony 7. I haven't had time to look into that in detail, but as long as that job is failing I am not comfortable just tagging a new version.

**Comment by benconda** [comment]
Hi, just added a PR to fix the broken test : https://github.com/ibericode/vat-bundle/pull/15

**Comment by dannyvankooten** [comment]
Awesome, thank you

**Comment by dannyvankooten** [comment]
Version 2.1.0 was just tagged 🎉
